import { useState, useCallback } from "react";
import { useContract } from "@/hooks/useContract";
import { useWallet } from "@/context/WalletContext";
import { CONTRACT_ADDRESSES } from "@/utils/constants";

/**
 * useRwaToken — hook for interacting with the rwa_token ink! contract
 *
 * Wraps useContract with RWA-specific methods:
 *   - getMetadata()        → full asset metadata struct
 *   - getBalance(address)  → token balance of an address
 *   - mint(params)         → deploy a new RWA token contract
 *   - transfer(to, amount) → transfer fractions
 *   - approve(spender, amount) → approve marketplace to move tokens
 *   - updateValue(newValue) → update asset USD value
 *   - setStatus(status)    → freeze/unfreeze asset
 *
 * Usage:
 *   const { getMetadata, transfer, isLoading } = useRwaToken(contractAddress, abi);
 */

// Minimal ABI for the rwa_token contract
// Full ABI is generated by `cargo contract build` in target/ink/rwa_token.json
// This is a simplified version for demonstration
const RWA_TOKEN_ABI = {
  source: {},
  contract: { name: "rwa_token", version: "0.1.0" },
  spec: {
    messages: [
      { label: "total_supply",   selector: "0x162df8c2", args: [],                           returnType: { type: "Balance" } },
      { label: "balance_of",    selector: "0x6568382f", args: [{ type: "AccountId" }],       returnType: { type: "Balance" } },
      { label: "get_metadata",  selector: "0x3d261bd4", args: [],                             returnType: { type: "AssetMetadata" } },
      { label: "transfer",      selector: "0x84a15da1", args: [{ type: "AccountId" }, { type: "Balance" }], returnType: { type: "Result" } },
      { label: "approve",       selector: "0x681266a0", args: [{ type: "AccountId" }, { type: "Balance" }], returnType: { type: "Result" } },
      { label: "update_value",  selector: "0x2a25f4de", args: [{ type: "u128" }],            returnType: { type: "Result" } },
      { label: "set_status",    selector: "0x1e77e3a4", args: [{ type: "AssetStatus" }],     returnType: { type: "Result" } },
    ],
  },
};

export function useRwaToken(contractAddress, customAbi) {
  const abi = customAbi || RWA_TOKEN_ABI;
  const { query, tx, isReady, error } = useContract(contractAddress, abi);
  const { selectedAccount }           = useWallet();

  const [isLoading, setIsLoading] = useState(false);
  const [txError,   setTxError]   = useState(null);

  // ── Read: get full asset metadata ─────────────────────────────
  const getMetadata = useCallback(async () => {
    try {
      return await query("get_metadata", []);
    } catch (err) {
      console.error("[useRwaToken] getMetadata:", err);
      return null;
    }
  }, [query]);

  // ── Read: get token balance of an address ─────────────────────
  const getBalance = useCallback(async (address) => {
    try {
      const addr = address || selectedAccount?.address;
      if (!addr) return "0";
      return await query("balance_of", [addr]);
    } catch (err) {
      console.error("[useRwaToken] getBalance:", err);
      return "0";
    }
  }, [query, selectedAccount]);

  // ── Read: total token supply ───────────────────────────────────
  const getTotalSupply = useCallback(async () => {
    try {
      return await query("total_supply", []);
    } catch (err) {
      console.error("[useRwaToken] getTotalSupply:", err);
      return "0";
    }
  }, [query]);

  // ── Write: transfer fractions to another address ───────────────
  const transfer = useCallback(async (to, amount) => {
    setIsLoading(true);
    setTxError(null);
    try {
      const result = await tx("transfer", [to, amount]);
      return result;
    } catch (err) {
      setTxError(err.message);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [tx]);

  // ── Write: approve marketplace to spend tokens ─────────────────
  // Must be called before listing on marketplace
  const approve = useCallback(async (spender, amount) => {
    setIsLoading(true);
    setTxError(null);
    try {
      const result = await tx("approve", [spender, amount]);
      return result;
    } catch (err) {
      setTxError(err.message);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [tx]);

  // ── Write: update asset USD value (owner only) ─────────────────
  const updateValue = useCallback(async (newValueCents) => {
    setIsLoading(true);
    setTxError(null);
    try {
      // Value stored in cents to avoid floating point
      const result = await tx("update_value", [newValueCents]);
      return result;
    } catch (err) {
      setTxError(err.message);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [tx]);

  // ── Write: freeze or unfreeze an asset (owner only) ────────────
  // status: 0=Active 1=Pending 2=Frozen
  const setStatus = useCallback(async (status) => {
    setIsLoading(true);
    setTxError(null);
    try {
      const result = await tx("set_status", [status]);
      return result;
    } catch (err) {
      setTxError(err.message);
      throw err;
    } finally {
      setIsLoading(false);
    }
  }, [tx]);

  return {
    isReady,
    isLoading,
    error:    error || txError,
    // Read methods
    getMetadata,
    getBalance,
    getTotalSupply,
    // Write methods
    transfer,
    approve,
    updateValue,
    setStatus,
  };
}
